In [1]:
import pickle

In [2]:
import numpy as nm
import matplotlib.pyplot as mtp

In [3]:
import pandas as pd
from sklearn import preprocessing
obj = preprocessing.LabelEncoder()

data = pd.read_csv('./Sample_DS - Sheet1.csv')
data = pd.DataFrame(data)
encoders = {}

for i in data:
    obj = preprocessing.LabelEncoder()
    data[i]= obj.fit_transform(data[i])
    encoders[i] = obj
    # print(i)
    print(sorted(data[i].unique()))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 

In [4]:
pickle.dump(encoders,open('LabelEncoder.pkl','wb'))

Decision Tree

In [5]:
x= data.iloc[:, [0,1]].values
y= data.iloc[:, 2].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)



In [6]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(x_train, y_train)

y_pred= classifier.predict(x_test)

In [7]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
cm

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [ ]:
# from matplotlib.colors import ListedColormap
# x_set, y_set = x_test, y_test
# x1, x2 = nm.meshgrid(nm.arange(start = x_set[:, 0].min() - 1, stop = x_set[:, 0].max() + 1, step  =0.01),
# nm.arange(start = x_set[:, 1].min() - 1, stop = x_set[:, 1].max() + 1, step = 0.01))
# mtp.contourf(x1, x2, classifier.predict(nm.array([x1.ravel(), x2.ravel()]).T).reshape(x1.shape),
# alpha = 0.75, cmap = ListedColormap(('purple','green' )))
# mtp.xlim(x1.min(), x1.max())
# mtp.ylim(x2.min(), x2.max())
# for i, j in enumerate(nm.unique(y_set)):
#         mtp.scatter(x_set[y_set == j, 0], x_set[y_set == j, 1],
#         c = ListedColormap(('purple', 'green'))(i), label = j)
# mtp.title('Decision Tree Algorithm(Test set)')
# # mtp.xlabel('Age=')
# # mtp.ylabel('Estimated Salary')
# mtp.legend()
# mtp.show()

In [8]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00       0.0
           6       0.00      0.00      0.00       1.0
           9       0.00      0.00      0.00       0.0
          12       0.00      0.00      0.00       1.0
          16       0.00      0.00      0.00       1.0
          17       0.00      0.00      0.00       1.0
          18       0.00      0.00      0.00       1.0
          19       0.00      0.00      0.00       0.0
          21       0.00      0.00      0.00       1.0
          22       0.00      0.00      0.00       0.0
          25       0.00      0.00      0.00       1.0
          27       0.00      0.00      0.00       1.0
          28       0.00      0.00      0.00       0.0
          29       0.00      0.00      0.00       0.0
          31   

c:\Users\haris\.conda\envs\cv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\haris\.conda\envs\cv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\haris\.conda\envs\cv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\haris\.conda\envs\cv\lib\site-packages\

In [9]:
results = pd.DataFrame({'Incident':x_test[:,0],'tYPE':x_test[:,1],'B': y_pred})

In [ ]:
results


Incident  tYPE    B
0          2   152  344
1          6   104  272
2         12    42   56
3          4   117  322
4         12     2   32
..       ...   ...  ...
85         1     6  175
86         3    29   66
87         5    56  112
88        12     2   32
89        10    74  143

[90 rows x 3 columns]

In [ ]:
# query = ['Routing Protocol Flap' ,	'EIGRP neighbors frequently resetting.']
# query[0]= encoders['Type'].transform([query[0]])
# query[1]= encoders['Incident'].transform([query[1]])
# arr=[query[0],query[1]]

# querys = pd.DataFrame({'Incident':query[1]})
# querys
# data1 = classifier.predict(querys)
# data1 = encoders['Resolution'].inverse_transform(data1)
# data1

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


array(['Implement a configuration management process, conduct regular security audits, and follow best practices for access point settings.'],
      dtype=object)

In [10]:
pickle.dump(classifier, open('hotspot_model.pkl', 'wb'))

In [11]:
t=pickle.load(open('hotspot_model.pkl', 'rb'))

In [12]:
query = ['Denial of Service (DoS) Attacks' ,	"Botnet Attacks Description: Large networks of compromised devices are used to launch attacks."]
query[0]= encoders['Type'].transform([query[0]])
query[1]= encoders['Incident'].transform([query[1]])
arr=[query[0],query[1]]

querys = pd.DataFrame({'Type':query[0],'Incident':query[1]})
querys
data1 = t.predict(querys)
data1 = encoders['Resolution'].inverse_transform(data1)
data1

c:\Users\haris\.conda\envs\cv\lib\site-packages\sklearn\base.py:457: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(


array(['Regularly update and patch devices, use intrusion detection systems, and employ IP reputation filtering.'],
      dtype=object)